FO_STOCKS = [
    "RELIANCE","TCS","INFY","HDFCBANK","ICICIBANK","SBIN","ADANIENT","WIPRO",
    "AXISBANK","BAJFINANCE","HCLTECH","LT","KOTAKBANK","TATAMOTORS","MARUTI",
    "SUNPHARMA","ITC","ONGC","POWERGRID","NTPC","BPCL","GRASIM","TITAN",
    "INDUSINDBK","ULTRACEMCO","HEROMOTOCO","ASIANPAINT","MM","DRREDDY",
    "DIVISLAB","CIPLA","TECHM","TATASTEEL","BAJAJFINSV","NESTLEIND",
    "HINDALCO","COALINDIA","VEDL","JSWSTEEL","SAIL","APOLLOHOSP",
    "PIDILITIND","SIEMENS","HAVELLS","VOLTAS",
    # ── Additional F&O stocks ──
    "BHARTIARTL","BANKBARODA","BEL","DLF","HAL","IRCTC","TATAPOWER",
    "TATACONSUM","TRENT","PNB","CANBK","SBILIFE","SBICARD","PFC","RECLTD",
    "BIOCON","LUPIN","JUBLFOOD","LICHSGFIN","MOTHERSON","CHOLAFIN",
    "MUTHOOTFIN","FEDERALBNK","UPL","POLYCAB","SRF","DABUR","GODREJCP",
    "BANDHANBNK","IDFCFIRSTB","INDUSTOWER","NAUKRI","BHARATFORG","COFORGE",
    "GODREJPROP","PETRONET","RBLBANK","TATACOMM","INDHOTEL","PAGEIND",
]
INDEX_SYMBOLS = ["NIFTY", "BANKNIFTY", "FINNIFTY"]

LOT_SIZES = {
    "NIFTY": 75, "BANKNIFTY": 30, "FINNIFTY": 65, "MIDCPNIFTY": 120,
    "RELIANCE": 250, "TCS": 175, "INFY": 400, "HDFCBANK": 550, "ICICIBANK": 700,
    "SBIN": 750, "ADANIENT": 500, "WIPRO": 1500, "AXISBANK": 625, "BAJFINANCE": 125,
    "HCLTECH": 350, "LT": 150, "KOTAKBANK": 400, "TATAMOTORS": 1425, "MARUTI": 100,
    "SUNPHARMA": 350, "ITC": 1600, "ONGC": 3075, "POWERGRID": 2700, "NTPC": 2250,
    "BPCL": 1800, "GRASIM": 250, "TITAN": 175, "INDUSINDBK": 500, "ULTRACEMCO": 100,
    "HEROMOTOCO": 150, "ASIANPAINT": 300, "MM": 350, "DRREDDY": 125,
    "BAJAJFINSV": 500, "HINDALCO": 1075, "TATASTEEL": 5500, "DIVISLAB": 150, "CIPLA": 650,
    "TECHM": 600, "NESTLEIND": 50, "COALINDIA": 2100, "VEDL": 1550, "JSWSTEEL": 675, "SAIL": 4700,
    "APOLLOHOSP": 125, "PIDILITIND": 500, "SIEMENS": 150, "HAVELLS": 500, "VOLTAS": 375,
    # ── Additional F&O stocks ──
    "BHARTIARTL": 475, "BANKBARODA": 2925, "BEL": 1950, "DLF": 825, "HAL": 150,
    "IRCTC": 575, "TATAPOWER": 1350, "TATACONSUM": 500, "TRENT": 75, "PNB": 4000,
    "CANBK": 4500, "SBILIFE": 375, "SBICARD": 400, "PFC": 1400, "RECLTD": 1500,
    "BIOCON": 1800, "LUPIN": 425, "JUBLFOOD": 1250, "LICHSGFIN": 775, "MOTHERSON": 3200,
    "CHOLAFIN": 375, "MUTHOOTFIN": 250, "FEDERALBNK": 5000, "UPL": 1300, "POLYCAB": 100,
    "SRF": 125, "DABUR": 1250, "GODREJCP": 500, "BANDHANBNK": 2400, "IDFCFIRSTB": 5000,
    "INDUSTOWER": 1600, "NAUKRI": 75, "BHARATFORG": 500, "COFORGE": 75, "GODREJPROP": 225,
    "PETRONET": 3000, "RBLBANK": 2800, "TATACOMM": 250, "INDHOTEL": 700, "PAGEIND": 15,
}

NSE_HEADERS = {
    "User-Agent":       "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "Accept":           "application/json, text/plain, */*",
    "Accept-Language":  "en-US,en;q=0.9",
    "Accept-Encoding":  "gzip, deflate, br",
    "Referer":          "https://www.nseindia.com/option-chain",
    "X-Requested-With": "XMLHttpRequest",
    "sec-ch-ua":        '"Chromium";v="122","Not(A:Brand";v="24","Google Chrome";v="122"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"macOS"',
    "sec-fetch-dest":   "empty",
    "sec-fetch-mode":   "cors",
    "sec-fetch-site":   "same-origin",
    "Connection":       "keep-alive",
    "Cache-Control":    "no-cache",
    "Pragma":           "no-cache",
}

SLUG_MAP = {
  "NIFTY": "nifty-50-share-price",
  "BANKNIFTY": "bank-nifty-share-price",
  "FINNIFTY": "nifty-financial",
  "RELIANCE": "reliance-industries-ltd-share-price",
  "TCS": "tata-consultancy-services-ltd-share-price",
  "INFY": "infosys-ltd-share-price",
  "HDFCBANK": "hdfc-bank-ltd-share-price",
  "ICICIBANK": "icici-bank-ltd-share-price",
  "SBIN": "state-bank-of-india-share-price",
  "ADANIENT": "adani-enterprises-ltd-share-price",
  "WIPRO": "wipro-ltd-share-price",
  "AXISBANK": "axis-bank-ltd-share-price",
  "BAJFINANCE": "bajaj-finance-ltd-share-price",
  "HCLTECH": "hcl-technologies-ltd-share-price",
  "LT": "larsen-and-toubro-ltd-share-price",
  "KOTAKBANK": "kotak-mahindra-bank-ltd-share-price",
  "TATAMOTORS": "tata-motors-passenger-vehicles-ltd-share-price",
  "MARUTI": "maruti-suzuki-india-ltd-share-price",
  "SUNPHARMA": "sun-pharmaceutical-industries-ltd-share-price",
  "ITC": "itc-ltd-share-price",
  "ONGC": "oil-and-natural-gas-corpn-ltd-share-price",
  "POWERGRID": "power-grid-corporation-of-india-ltd-share-price",
  "NTPC": "ntpc-ltd-share-price",
  "BPCL": "bharat-petroleum-corporation-ltd-share-price",
  "GRASIM": "grasim-industries-ltd-share-price",
  "TITAN": "titan-company-ltd-share-price",
  "INDUSINDBK": "indusind-bank-ltd-share-price",
  "ULTRACEMCO": "ultratech-cement-ltd-share-price",
  "HEROMOTOCO": "hero-motocorp-ltd-share-price",
  "ASIANPAINT": "asian-paints-ltd-share-price",
  "MM": "mahindra-and-mahindra-ltd-share-price",
  "DRREDDY": "dr-reddys-laboratories-ltd-share-price",
  "DIVISLAB": "divis-laboratories-ltd-share-price",
  "CIPLA": "cipla-ltd-share-price",
  "TECHM": "tech-mahindra-ltd-share-price",
  "TATASTEEL": "tata-steel-ltd-share-price",
  "BAJAJFINSV": "bajaj-finserv-ltd-share-price",
  "NESTLEIND": "nestle-india-ltd-share-price",
  "HINDALCO": "hindalco-industries-ltd-share-price",
  "COALINDIA": "coal-india-ltd-share-price",
  "VEDL": "vedanta-ltd-share-price",
  "JSWSTEEL": "jsw-steel-ltd-share-price",
  "SAIL": "steel-authority-of-india-ltd-share-price",
  "APOLLOHOSP": "apollo-hospitals-enterprise-ltd-share-price",
  "PIDILITIND": "pidilite-industries-ltd-share-price",
  "SIEMENS": "siemens-ltd-share-price",
  "HAVELLS": "havells-india-ltd-share-price",
  "VOLTAS": "voltas-ltd-share-price",
  "BHARTIARTL": "bharti-airtel-ltd-share-price",
  "BANKBARODA": "bank-of-baroda-share-price",
  "BEL": "bharat-electronics-ltd-share-price",
  "DLF": "dlf-ltd-share-price",
  "HAL": "hindustan-aeronautics-ltd-share-price",
  "IRCTC": "indian-railway-catering-tourism-corporation-ltd-share-price",
  "TATAPOWER": "tata-power-company-ltd-share-price",
  "TATACONSUM": "tata-consumer-products-ltd-share-price",
  "TRENT": "trent-ltd-share-price",
  "PNB": "punjab-national-bank-share-price",
  "CANBK": "canara-bank-share-price",
  "SBILIFE": "sbi-life-insurance-company-ltd-share-price",
  "SBICARD": "sbi-cards-and-payment-services-ltd-share-price",
  "PFC": "power-finance-corporation-ltd-share-price",
  "RECLTD": "rec-ltd-share-price",
  "BIOCON": "biocon-ltd-share-price",
  "LUPIN": "lupin-ltd-share-price",
  "JUBLFOOD": "jubilant-foodworks-ltd-share-price",
  "LICHSGFIN": "lic-housing-finance-ltd-share-price",
  "MOTHERSON": "samvardhana-motherson-international-ltd-share-price",
  "CHOLAFIN": "cholamandalam-investment-and-finance-company-ltd-share-price",
  "MUTHOOTFIN": "muthoot-finance-ltd-share-price",
  "FEDERALBNK": "federal-bank-ltd-share-price",
  "UPL": "upl-ltd-share-price",
  "POLYCAB": "polycab-india-ltd-share-price",
  "SRF": "srf-ltd-share-price",
  "DABUR": "dabur-india-ltd-share-price",
  "GODREJCP": "godrej-consumer-products-ltd-share-price",
  "BANDHANBNK": "bandhan-bank-ltd-share-price",
  "IDFCFIRSTB": "idfc-first-bank-ltd-share-price",
  "INDUSTOWER": "indus-towers-ltd-share-price",
  "NAUKRI": "info-edge-india-ltd-share-price",
  "BHARATFORG": "bharat-forge-ltd-share-price",
  "COFORGE": "coforge-ltd-share-price",
  "GODREJPROP": "godrej-properties-ltd-share-price",
  "PETRONET": "petronet-lng-ltd-share-price",
  "RBLBANK": "rbl-bank-ltd-share-price",
  "TATACOMM": "tata-communications-ltd-share-price",
  "INDHOTEL": "indian-hotels-co-ltd-share-price",
  "PAGEIND": "page-industries-ltd-share-price"
}

INDSTOCKS_BASE = "https://stocks.indmoney.com"
NSE_BASE = "https://www.nseindia.com"

# Auto paper trading caps (None => unlimited)
MAX_DAILY_AUTO_TRADES = None
MAX_SECTOR_TRADES = None

# NSE symbol → Yahoo Finance ticker overrides (used by technical scoring)
YFINANCE_TICKER_MAP = {
    "NIFTY": "^NSEI",
    "BANKNIFTY": "^NSEBANK",
    "FINNIFTY": "NIFTY_FIN_SERVICE.NS",
}
